### ISSUE TITLE
options.colors property is not working

### ISSUE THREAD

**Issue by guzmanvig** [Lattice-Automation/seqviz#106]
Setting an array of colors in this property doesn't change the default annotation colors. However, setting a "color" property on each annotation works, but this functionality is not documented.

**Comment by jjti** [comment]
fixed in 3.0.38, added examples of colors to README

**Comment by Midnighter** [comment]
I'm on seqviz 3.0.43 and I still have problems with this. I use it with React and a Genbank file from string. Changing the colors prop has no effect, for example,

```js
<SeqViz file={genbank} colors={['#DDDDDD']} />
```

uses the default colors.
