### ISSUE TITLE
Plans to add TypeScript support?

### ISSUE THREAD

**Issue by Midnighter** [Lattice-Automation/seqviz#116]
Hi, as the title says, I'm wondering if there are plans to support TypeScript in the near future? Also, the seqviz package depends on React 16.8 while the current version is 17.

Thanks for the info.

**Comment by jjti** [comment]
I'm starting on adding a change to allow React 17 as a peer dependency (which AFAIK shouldn't break anything, but I need to test): `^16.0.0 || ^17.0.0`

That led me down a build tooling rabbit hole and I'm now replacing webpack with esbuild. Will update soonish

**Comment by Midnighter** [comment]
Awesome that you're taking this on so quickly. Sorry to hear that it is giving you trouble, though.

**Comment by Benedict-Carling** [comment]
Hi great project @JJTimmons. I was planning on submitting a conversion to typescript PR, would this be considered for merging?

**Comment by jjti** [comment]
> Hi great project @JJTimmons. I was planning on submitting a conversion to typescript PR, would this be considered for merging?

Yeah of course, by all means and thanks

**Comment by jjti** [comment]
hey @Benedict-Carling I'm wondering if you started work on this? There are a couple upcoming changes/refactors, and any changes will cause a headache for a Typescript switchover. Would like to get that in first, if at all possible. I can also look at this again closer

**Comment by jjti** [comment]
> Also, the seqviz package depends on React 16.8 while the current version is 17.

I just addressed this in latest patch, please let me know if that helps

**Comment by Midnighter** [comment]
I don't know due to which change this is exactly but now my custom color palette is working. Before, it would always use the defaults. So that's great 🙂 

I still get the following warning in development. Not sure if it comes from seqviz or react-sizeme.

[find_dom_node.log](https://github.com/Lattice-Automation/seqviz/files/7574637/find_dom_node.log)

And the npm incompatibility warnings are gone. I'm quite happy 🙂

**Comment by jjti** [comment]
working on the TypeScript @Benedict-Carling, last couple commits added tsc and converted a couple files to TS (albeit with some hacks). Full code base will take awhile.

And re: DOM node find it's unfortunately size-me. Issue open for that package: https://github.com/ctrlplusb/react-sizeme/issues/199

**Comment by ninjha01** [comment]
Looks like https://github.com/Lattice-Automation/seqviz/commit/e8d5fa26253ea60d70690f1991eb2ca39496f42a closes this.

**Comment by jjti** [comment]
Still open, typescript is only in the package is a superficial sense. Actual types still need to be fixed and ts-ignores removed (piecemeal)

**Comment by ninjha01** [comment]
Ah I see - is that something you plan on taking? I'm happy to take that off your plate - I imagine it's a good way for me to get acquainted with the codebase.

**Comment by jjti** [comment]
All you, I haven't made progress past the initial TS migration (and TS-ification of a few helper files)
